### ISSUE TITLE
DMCA preamble

### ISSUE THREAD

**Issue by alexhultman** [ClusterWS/uWS#5]
I just stumbled upon this project and your licensing is completely pulled from thin air.

You'll get a DMCA takedown notice soon unless copyright issues are fixed. Essentially you are breaking clause 1, 2 and 3 of the Zlib license.

You can read more about how Zlib works here: https://en.wikipedia.org/wiki/Zlib_License

Edit: I guess it's only clause 2. Clause 1 is arguable though, could be a lot more obvious in LICENSE file.

**Comment by goriunov** [comment]
All right i will try to make it more licence based:

1. README contains a line which is `This module is modified version of the uWebSockets with some minor tweaks in C++ code and complete rewrite of JS code to TS.`. Also contains a link to the original software in the line `Modified version of uWebSockets`.

2. README contains a line which is `This module is modified version of the uWebSockets with some minor tweaks in C++ code and complete rewrite of JS code to TS.`  This is a notice that it is not an original software but Altered source versions.

3. [src](https://github.com/ClusterWS/uWS/tree/master/src) folder contain  [LICENCE](https://github.com/ClusterWS/uWS/blob/master/src/LICENSE) which were provided from main src of uWS.

If you would like i can move your licence to the `root` to make it more clear, it will have a dual license in the root.

**Comment by goriunov** [comment]
I have added some more clarifications about LICENCE and original software to README. Now you should see a line `Original software is available in uWebSockets repository.` with a link to the main src and `This repository is based on the uWebSockets therefore has two licence ClusterWS MIT and Alex Hultman ZLIB.` with links to the proper license in the repo. Also i have added reference to ZLIB license in to the LICENSE file. These and above things should cover clause `1`, `2`, and `3` properly and be more clear about what and where.

**Comment by alexhultman** [comment]
Honestly I jumped the gun a bit here. I have seen others completely crap on my copyright before and at first I did not even find src/LICENSE and assumed the worst. Sorry about that.

I think the only real issue is that src/LICENSE is unmodified, yet the code is modified. Basically you cannot put my name and my copyright on something I have not done. Clause 2 is very clear about this. You can put some line in src/LICENSE that states it is a fork and not the original and I'm perfectly happy with that.

**Comment by goriunov** [comment]
Alright will do that today :)

**Comment by alexhultman** [comment]
👍
